spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.56.116:5432/postgres
    username: postgres
    password: 12345678

mybatis:
  mapper-locations: classpath:*.xml
